### ISSUE TITLE
Installation fails due to Update of node-red-dashboard (2.24.0)

### ISSUE THREAD

**Issue by judalvarezca** [Adorkable/node-red-contrib-ui-led#58]
I'm installing today the node in a new docker container, but when executing my installation script there was some dependencies problems, due to the newly updated node-red-dashboard 5 days ago.

I guess in the meantime I'll keep using the 2.23.0 version, but an update on the node will be appreciated.

Thanks, have a very good day :)

**Comment by yoiang** [comment]
Oh interesting, has something changed with how **node-red-dashboard** operates? Do you have the logs by any chance?

**Comment by yoiang** [comment]
I've just pushed a new rewritten version [0.4.2](https://github.com/Adorkable/node-red-contrib-ui-led/releases/tag/0.4.2) using the latest node-red and node-red-dashboard.

Let me know if this resolves the issue for you, if not can you see if there are any logs in the browser console or in the Node-RED console?

Since I haven't heard back previously I'm going to close for now!
