### ISSUE TITLE
Node configuration marked as invalid after update to 0.4.2

### ISSUE THREAD

**Issue by Just-another-pleb** [Adorkable/node-red-contrib-ui-led#63]
Um, sorry, but now it is installed (the latest version) all instances of the LED are now "invalid" and I have to edit the nodes.

So now I have to go and edit all the existing nodes.

Is this right?

It looks like the colours are honored (luckily) but for reasons unknown I have to go and edit every node.

It seems that the LEDs no longer support 1x1 size.

RasPi Z (W) Jessie
LED version 0.4.2
NR 1.2.6
Dashboard 2.26.x
One has .0 and the other has .1

A few pictures to show.

Ok, sorry about one.   RED colours mean BAD.   GREEN colours mean GOOD.
One I goofed and did RED when it should be GREEN.

![Screenshot from 2021-01-13 10-43-52](https://user-images.githubusercontent.com/39888280/104388335-18d08300-558d-11eb-953c-407c9d62713f.png)
![Screenshot from 2021-01-13 10-43-59](https://user-images.githubusercontent.com/39888280/104388339-1a9a4680-558d-11eb-9660-0b758a43e09e.png)
![Screenshot from 2021-01-13 10-44-09](https://user-images.githubusercontent.com/39888280/104388341-1b32dd00-558d-11eb-95ac-ab88a4c7fcd5.png)
![Screenshot from 2021-01-13 10-44-35](https://user-images.githubusercontent.com/39888280/104388347-1bcb7380-558d-11eb-8cd1-3f44fa389e3f.png)
![Screenshot from 2021-01-13 10-44-39](https://user-images.githubusercontent.com/39888280/104388350-1cfca080-558d-11eb-9b6d-0ed8ded294cb.png)
![Screenshot from 2021-01-13 10-45-04](https://user-images.githubusercontent.com/39888280/104388354-1e2dcd80-558d-11eb-9c0e-bb08a3b3a5a2.png)
![Screenshot from 2021-01-13 10-45-08](https://user-images.githubusercontent.com/39888280/104388358-1f5efa80-558d-11eb-8ceb-042378158e30.png)

**Comment by yoiang** [comment]
Arg hmmm what did that. Can you send me a snippet of the flow where a node is marked invalid?

**Comment by Just-another-pleb** [comment]
It becomes "invalid" as soon as I change it form `1x1 size to `2x1` (horizontal)

**Comment by Just-another-pleb** [comment]
Ok, update:

Updated dashboard to latest.   Restarted NR.

Same.

Details:
RasPi Z (W) Jessie
NR 1.2.6
Dashboard 2.26.2
LED 0.4.2

Here's the scenario in pictures.

![Screenshot from 2021-01-13 11-29-49](https://user-images.githubusercontent.com/39888280/104390956-f93c5900-5592-11eb-9871-1264e40cacde.png)
![Screenshot from 2021-01-13 11-29-57](https://user-images.githubusercontent.com/39888280/104390958-fa6d8600-5592-11eb-8342-75e50ea027cf.png)
![Screenshot from 2021-01-13 11-30-01](https://user-images.githubusercontent.com/39888280/104390961-fb9eb300-5592-11eb-9ab2-2094efd93a34.png)
![Screenshot from 2021-01-13 11-30-07](https://user-images.githubusercontent.com/39888280/104390964-fc374980-5592-11eb-933b-48c76d7dbdbd.png)
![Screenshot from 2021-01-13 11-30-09](https://user-images.githubusercontent.com/39888280/104390968-fccfe000-5592-11eb-9575-ca2e168e2c62.png)

Now the other machine:

![Screenshot from 2021-01-13 11-33-13](https://user-images.githubusercontent.com/39888280/104391115-533d1e80-5593-11eb-8b08-7821756548e3.png)
![Screenshot from 2021-01-13 11-33-16](https://user-images.githubusercontent.com/39888280/104391119-5506e200-5593-11eb-9199-68021c10e16d.png)
![Screenshot from 2021-01-13 11-33-20](https://user-images.githubusercontent.com/39888280/104391123-559f7880-5593-11eb-8f72-a0d0d3400c85.png)

**Comment by yoiang** [comment]
I just pushed 0.4.3 which simplified the editor validation code, let me know if this resolves the issue! You might have to go into the node's config panel or even change a value to refresh the validators.

**Comment by Just-another-pleb** [comment]
You beauty!

Works!
(I'll let you close it if you are happy)

**Comment by yoiang** [comment]
Rock! Sorry about it breaking, thanks for your patience and working with me on testing it.

Of course, happy that you're interested! I finally got around to something I'd wanted to for a bit with the library. I'm not sure how computer science familiar you are but the library, just like Node-RED was originally written in Javascript. For maintenance and new feature development purposes I finally got around to rewriting it in Typescript.  I'd be happy to share the difference between the two or my personal opinions if you aren't familiar! 

One of the more important things it did was iron out some of the hacky or ambiguous code that one can get away with in Javascript, which meant things like the editor field validation code had to be thoroughly clarified. When a node is first created and whenever you tab away from a field in the node config panel this code says yay or nay about the value that the user entered and gives the node the opportunity to prompt the user (right now we're just doing the red border highlights). In clarifying the validation code I thought I had translated my original intention but because Javascript's grammar has baked into it certain ambiguities (some of which I could have and should have avoided in the first place) and it was written so long ago I had forgotten my original intent. Rather than sitting down and deciding what it should do I was trying to translate what was there into what I had thought it was meant to do. So today I did that, sat down and decided on how it should behave now. And in the future when I or someone else comes back after a long time/for the first time Typescript and how I wrote it makes it much harder to misinterpret!
