### ISSUE TITLE
Improvement: Add node status

### ISSUE THREAD

**Issue by m-schaeffler** [Adorkable/node-red-contrib-ui-led#69]
I'm suggesting to add a node state to show in the node red editor the last received state.

**Comment by yoiang** [comment]
Hey @m-schaeffler , thank you for the suggestion! There is a previous issues that represents this feature (#6) that ultimately I closed because I figured this would mostly be used for debugging purposes while setting up one's dashboard and mostly duplicate's other debugging nodes' functionality.

However you have a super compelling reason or enough people call for it maybe we should reconsider!
